{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "timesheet-filler.fullname" . }}
  labels:
    {{- include "timesheet-filler.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "timesheet-filler.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: {{ .Values.prometheus.path | default "/metrics" }}
    interval: {{ .Values.prometheus.serviceMonitor.interval | default "30s" }}
    {{- if .Values.prometheus.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml .Values.prometheus.serviceMonitor.metricRelabelings | nindent 4 }}
    {{- end }}
    {{- if .Values.prometheus.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.prometheus.serviceMonitor.relabelings | nindent 4 }}
    {{- end }}
{{- end }}
